# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    # depends_on:
    #   - rabbitmq
    networks:
      - my-default-rabbit

  queue:
    build: .
    command: python consumer.py
    # depends_on:
    #   - rabbitmq
    networks:
      - my-default-rabbit

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   hostname: my-rabbit
  #   container_name: 'rabbitmq2'
  #   ports:
  #     - 5673:5673
  #     - 15673:15673
  #   networks:
  #     - my-default-rabbit

networks: 
  my-default-rabbit:
    name: my-default-rabbit
    external: true        