# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # depends_on:
    #   - rabbitmq
    networks:
      - my-default-rabbit

  queue:
    build: .
    command: python consumer.py
    # depends_on:
    #   - rabbitmq
    networks:
      - my-default-rabbit

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   hostname: my-rabbit
  #   container_name: 'rabbitmq'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   networks:
  #     - my-default-rabbit

networks: 
  my-default-rabbit:
    name: my-default-rabbit
    external: true